name: DisplayModelPlugin
version: '${version}'
main: me.aneleu.displaymodel.DisplayModelPlugin
api-version: '1.20'
commands:
  display:
    description: display entity manage command
  model:
    description: display model manage command